apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
  name: {{ include "nginx.name" . }}
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: {{ .Values.protocol }}
    targetPort: {{ .Values.port }}
  selector:
    name: {{ include "nginx.name" . }}
  type: {{ .Values.type }}
status:
  loadBalancer: {}
